title: Hi~ I am here!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: zhanbs # add your name
author-img: bushang.png # add your photo
about-author: I am a graduate student at Northeastern University, Boston. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: zhanbs # add your Github handle
linkedin: # add your Linkedin handle
email: bushang.zhan@gmail.com # add your Email address

# Disqus
discus-identifier: zhanbs # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

encoding: utf-8

port: 12346

favicon: favicon.ico